### ISSUE TITLE
Using java socket client

### ISSUE THREAD

**Issue by bromoapp** [DarkRiftNetworking/DarkRift#161]
Hi, I need to create a bot server to deploy many game bots using Java instead of Unity app (C#) to connect to Darkrift. 

I download Darkrift Server through Unity import and running the sample server that bundled under DarkRift Server (.NET Framework 4.0) zip file. When I run sample unity app (chat app) the console shows my chat app successfully connected.

So I try to connect using Java socket client, but there is nothing print out on the console.
Do you have any idea on how to connect to Darkrift using other tech stack besides C#? or how can I reproduce how C# Darkrift client class processing the connection to Darkrift?

Thanks

**Comment by JamJar00** [comment]
DarkRift has it's own protocol you'll need to imlement on the Java side in order to connect.

There's two layers to it: The Bichannel listener protocol which is contained in [this file](https://github.com/DarkRiftNetworking/DarkRift/blob/master/DarkRift.Client/BichannelClientConnection.cs) and handles the sockets, and the Message protocol which is in [this file](https://github.com/DarkRiftNetworking/DarkRift/blob/master/DarkRift/Message.cs) (plus the DarkRiftWriter/Readers).

I know someone's done a Python implementation, so if you get a Java one going please do consider making it open source for the rest of the community!

**Comment by bromoapp** [comment]
Sure I will contribute my java client... no worries at all
