### ISSUE TITLE
DarkRift 2.4.3 BlockDemo Doesnt spawn players

### ISSUE THREAD

**Issue by TheNocturnalDev** [DarkRiftNetworking/DarkRift#79]
### Quick Description
DarkRift 2.4.3 BlockDemo doesnt spawn players when loading, no errors in logs, no errors in unity

#### For Issues
Download Latest version from unity asset store,
Download BlockDemoPlugin repo/Compile
Install plugin on server, start server
Start BlockDemo in unity

[14-41-31 PM.txt](https://github.com/DarkRiftNetworking/DarkRift/files/3214291/14-41-31.PM.txt)

![image](https://user-images.githubusercontent.com/28176352/58289036-1db64280-7d6a-11e9-8c31-2f794d4653cd.png)

**Comment by JamJar00** [comment]
Hi SymphonicDev1,

I'm hoping that this is fixed in 2.4.5 (at least, I can't reproduce it!), would you be able to give it a go just in case there's something specific you were doing that I'm not that was causing these issues?

You can download 2.4.5 here:
https://www.darkriftnetworking.com/DarkRift2/Releases/Free/2.4.5.unitypackage
https://www.darkriftnetworking.com/DarkRift2/Releases/Pro/2.4.5.unitypackage?invoice=<your invoice number>

Jamie

**Comment by TheNocturnalDev** [comment]
sorry for taking so long, but it appears to be fixed, thank you
